services:
  ui:
    build:
      context: ./wishr-ui
    volumes:
      - /etc/ssl:/etc/ssl
    ports:
      - "3000:80" # Map container port to host port for UI
    depends_on:
      - api # Wait for api to be up
  api:
    build:
      context: ./wishr-api
    volumes:
      - ./storage:/storage
    ports:
      - "3001:3001" # Map container port to host port for API
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    depends_on:
      - postgres # Wait for db to be up
  postgres:
    build:
      context: ./wishr-db
    ports:
      - "3002:5432" # Map container port to host port
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
